baseURL = "https://oliver-lehner.github.io/creative-portfolio/"
languageCode = "en-us"
title = "Oliver Lehner"
theme = "bslol"
copyright = "Oliver Lehner"


[taxonomies]
	category = "categories"
	tag = "tags"
